version: "3.9"
services:
  mego_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego_api
    depends_on:
      - postgres
      - redis
    ports:
      - "${API_SERVICE_SERVER_PORT}:${API_SERVICE_SERVER_PORT}"
    networks:
      - mego_network

networks:
  mego_network:
    external: true